repos:

- repo: https://github.com/pycqa/isort
  rev: 5.11.2
  hooks:
  - id: isort
    additional_dependencies: [toml]
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    additional_dependencies:
    - types_markdown
    - types-bleach
    - types-pytz
    - types-python-dateutil
    - types-requests
- repo: https://github.com/pycqa/pylint
  rev: v2.15.8
  hooks:
  - id: pylint
    additional_dependencies: [toml]
