#!/usr/bin/env python3
import os
import typing as t
from jinja2 import Environment, FileSystemLoader


def _render(env: t.Any, template: str, output: str, **kwargs: t.Any) -> None:
    target_path = 'public/' + output
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    with open(target_path, 'w', encoding='utf-8') as handle:
        handle.write(env.get_template(template).render(**kwargs))


def _render_news(env: t.Any) -> None:
    _render(env, template='news.html', output='index.html')


def _render_releases(env: t.Any) -> None:
    _render(env, template='releases.html', output='releases.html')


def _render_about(env: t.Any) -> None:
    _render(env, template='about.html', output='about.html')


def main() -> None:
    env = Environment(loader=FileSystemLoader('html'))
    _render_news(env)
    _render_releases(env)
    _render_about(env)


if __name__ == '__main__':
    main()
