version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./services/app/Dockerfile
    command: uwsgi
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./app:/app
      - ./services/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=oc_website.settings
      - SECRET_KEY=change_me  # change this in docker-compose.override.yml
      - DEBUG

  redis:
    image: redis:6
    expose:
      - 6379

  celery:
    build:
      context: .
      dockerfile: ./services/app/Dockerfile
    command: celery
    volumes:
      - ./app:/app
      - ./services/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
    environment:
      - SECRET_KEY=change_me  # change this in docker-compose.override.yml
      - DEBUG

volumes:
  pgdata:
