[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["oc_website"]

[tool.mypy]
disallow_untyped_decorators = false
python_version = "3.9"

[tool.pylint.master]
jobs = 0

[tool.pylint.message_control]
disable = [
    "import-error",  # for pre-commit, which cannot install external modules
    "missing-docstring",
    "too-few-public-methods",
    "no-self-use",
    "no-member",  # leave that to mypy
    "useless-return",  # false positives for `return None` that conflict with mypy
    "fixme",
]
module-rgx="(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+)|([0-9]{4}_[a-z_][a-z0-9_]*))$"
