#!/usr/bin/env python
import os
import re
import subprocess
from pathlib import Path


def main():
    news_files = list(sorted((Path(__file__).parent / 'news').iterdir()))
    last_news_path = news_files[-1]
    last_news_id = int(re.search(r'(\d+)', str(last_news_path)).group(1))
    next_news_path = last_news_path.parent / f'{last_news_id + 1:04}.html'
    if next_news_path.exists():
        raise RuntimeError('Can\'t figure out next news path')
    subprocess.run([os.environ['EDITOR'] or 'vim', next_news_path])


if __name__ == '__main__':
    main()
