# Generated by Django 3.2.6 on 2021-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_date", models.DateTimeField()),
                ("image", models.FileField(upload_to="featured_images/")),
            ],
        ),
    ]
