# Generated by Django 3.2.6 on 2021-08-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0002_featuredimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="big_image",
            field=models.FileField(default=None, upload_to="projects/big/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="small_image",
            field=models.FileField(default=None, upload_to="projects/small/"),
            preserve_default=False,
        ),
    ]
