# Generated by Django 3.2.6 on 2021-08-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0004_alter_projectreleaselink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="synopsis",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
