# Generated by Django 3.2.6 on 2021-08-19 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0005_auto_20210818_2242"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_date", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "news",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="featuredimage",
            options={"ordering": ["-feature_date"]},
        ),
        migrations.AlterModelOptions(
            name="projectrelease",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AlterModelOptions(
            name="projectreleasefile",
            options={"ordering": ["file_name"]},
        ),
        migrations.CreateModel(
            name="NewsAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="news/")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oc_website.news",
                    ),
                ),
            ],
        ),
    ]
