# Generated by Django 3.2.6 on 2021-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0006_auto_20210819_2002"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("request_date", models.DateTimeField(blank=True, null=True)),
                ("anidb_url", models.URLField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "remote_addr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
    ]
