# Generated by Django 3.2.6 on 2021-08-19 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0007_animerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.CharField(max_length=32)),
                ("comment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "remote_addr",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("text", models.TextField()),
                (
                    "author",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oc_website.comment",
                        related_name="child_comments",
                    ),
                ),
            ],
            options={
                "ordering": ["context", "-comment_date"],
            },
        ),
    ]
