# Generated by Django 3.2.6 on 2021-08-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="context",
            field=models.CharField(
                choices=[("guestbook", "guestbook"), ("news", "news")],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("finished", "finished")],
                max_length=30,
            ),
        ),
    ]
