# Generated by Django 3.2.6 on 2021-08-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0014_auto_20210828_1410"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animerequest",
            name="title",
        ),
    ]
