# Generated by Django 3.2.6 on 2021-08-28 22:09

import django.db.models.deletion
from django.db import migrations, models


def remove_non_guestbook_comments(apps, _schema_editor):
    Comment = apps.get_model(  # pylint: disable=invalid-name
        "oc_website", "Comment"
    )
    Comment.objects.filter(context__iexact="news").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("oc_website", "0015_remove_animerequest_title"),
    ]

    operations = [
        migrations.RunPython(
            remove_non_guestbook_comments, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-comment_date"]},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="context",
        ),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
