# Generated by Django 3.2.6 on 2021-11-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0016_auto_20210828_2209"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
