# Generated by Django 3.2.6 on 2021-12-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0017_comment_is_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="AniDBEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anidb_id", models.IntegerField()),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="anidb/"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("episodes", models.IntegerField(blank=True, null=True)),
                ("synopsis", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="anidbentry",
            options={
                "verbose_name": "AniDB entry",
                "verbose_name_plural": "AniDB entries",
            },
        ),
        migrations.AddField(
            model_name="animerequest",
            name="anidb_entry",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to="oc_website.anidbentry",
            ),
        ),
    ]
