# Generated by Django 3.2.6 on 2021-12-12 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_website", "0019_auto_20211212_1941"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_end_date",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_episodes",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_image",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_start_date",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_synopsis",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_title",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_type",
        ),
        migrations.RemoveField(
            model_name="animerequest",
            name="anidb_id",
        ),
    ]
